# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dat_client.api.actors_api import ActorsApi


class TestActorsApi(unittest.TestCase):
    """ActorsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ActorsApi()

    def tearDown(self) -> None:
        pass

    def test_create_actor_actors_post(self) -> None:
        """Test case for create_actor_actors_post

        Create Actor
        """
        pass

    def test_delete_actor_actors_actor_id_delete(self) -> None:
        """Test case for delete_actor_actors_actor_id_delete

        Delete Actor
        """
        pass

    def test_fetch_available_actors_actors_actor_type_list_get(self) -> None:
        """Test case for fetch_available_actors_actors_actor_type_list_get

        Fetch Available Actors
        """
        pass

    def test_get_actor_documentaion_actors_doc_get(self) -> None:
        """Test case for get_actor_documentaion_actors_doc_get

        Get Actor Documentaion
        """
        pass

    def test_get_actor_specs_actors_actor_id_spec_get(self) -> None:
        """Test case for get_actor_specs_actors_actor_id_spec_get

        Get Actor Specs
        """
        pass

    def test_mark_actor_inactive_actors_actor_id_mark_inactive_delete(self) -> None:
        """Test case for mark_actor_inactive_actors_actor_id_mark_inactive_delete

        Mark Actor Inactive
        """
        pass

    def test_read_actor_actors_actor_id_get(self) -> None:
        """Test case for read_actor_actors_actor_id_get

        Read Actor
        """
        pass

    def test_update_actor_actors_actor_id_put(self) -> None:
        """Test case for update_actor_actors_actor_id_put

        Update Actor
        """
        pass


if __name__ == '__main__':
    unittest.main()
