# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dat_client.models.stream_metadata import StreamMetadata

class TestStreamMetadata(unittest.TestCase):
    """StreamMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StreamMetadata:
        """Test StreamMetadata
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StreamMetadata`
        """
        model = StreamMetadata()
        if include_optional:
            return StreamMetadata(
                dat_source = None,
                dat_stream = None,
                dat_document_entity = None,
                dat_last_modified = None,
                dat_document_chunk = None
            )
        else:
            return StreamMetadata(
                dat_source = None,
                dat_stream = None,
        )
        """

    def testStreamMetadata(self):
        """Test StreamMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
