# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dat_api_sdk.models.destination_sync_mode import DestinationSyncMode

class TestDestinationSyncMode(unittest.TestCase):
    """DestinationSyncMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDestinationSyncMode(self):
        """Test DestinationSyncMode"""
        # inst = DestinationSyncMode()

if __name__ == '__main__':
    unittest.main()
