# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dat_client.api.workspaces_api import WorkspacesApi


class TestWorkspacesApi(unittest.TestCase):
    """WorkspacesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkspacesApi()

    def tearDown(self) -> None:
        pass

    def test_create_workspace_workspaces_post(self) -> None:
        """Test case for create_workspace_workspaces_post

        Create Workspace
        """
        pass

    def test_delete_workspace_workspaces_workspace_id_delete(self) -> None:
        """Test case for delete_workspace_workspaces_workspace_id_delete

        Delete Workspace
        """
        pass

    def test_fetch_available_workspaces_workspaces_list_get(self) -> None:
        """Test case for fetch_available_workspaces_workspaces_list_get

        Fetch Available Workspaces
        """
        pass

    def test_read_workspace_workspaces_workspace_id_get(self) -> None:
        """Test case for read_workspace_workspaces_workspace_id_get

        Read Workspace
        """
        pass

    def test_update_workspace_workspaces_workspace_id_put(self) -> None:
        """Test case for update_workspace_workspaces_workspace_id_put

        Update Workspace
        """
        pass


if __name__ == '__main__':
    unittest.main()
