# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dat_api_sdk.api.connection_run_logs_api import ConnectionRunLogsApi


class TestConnectionRunLogsApi(unittest.TestCase):
    """ConnectionRunLogsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectionRunLogsApi()

    def tearDown(self) -> None:
        pass

    def test_add_connection_run_log_connection_run_logs_post(self) -> None:
        """Test case for add_connection_run_log_connection_run_logs_post

        Add Connection Run Log
        """
        pass


if __name__ == '__main__':
    unittest.main()
