# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dat_client.models.actor_instance_get_response import ActorInstanceGetResponse

class TestActorInstanceGetResponse(unittest.TestCase):
    """ActorInstanceGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActorInstanceGetResponse:
        """Test ActorInstanceGetResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActorInstanceGetResponse`
        """
        model = ActorInstanceGetResponse()
        if include_optional:
            return ActorInstanceGetResponse(
                workspace_id = '',
                actor_id = '',
                user_id = '',
                name = '',
                actor_type = '',
                status = '',
                configuration = dat_client.models.configuration.Configuration(),
                id = '',
                actor = dat_client.models.actor_response.ActorResponse(
                    name = '', 
                    module_name = '', 
                    icon = '', 
                    actor_type = '', 
                    status = 'active', 
                    id = '', ),
                connected_connections = [
                    null
                    ]
            )
        else:
            return ActorInstanceGetResponse(
                workspace_id = '',
                actor_id = '',
                user_id = '',
                name = '',
                actor_type = '',
                status = '',
                id = '',
        )
        """

    def testActorInstanceGetResponse(self):
        """Test ActorInstanceGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
