# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.actors_api import ActorsApi


class TestActorsApi(unittest.TestCase):
    """ActorsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ActorsApi()

    def tearDown(self) -> None:
        pass

    def test_fetch_available_actors_actors_actor_type_list_get(self) -> None:
        """Test case for fetch_available_actors_actors_actor_type_list_get

        Fetch Available Actors
        """
        pass

    def test_get_actor_specs_actors_actor_uuid_specs_get(self) -> None:
        """Test case for get_actor_specs_actors_actor_uuid_specs_get

        Get Actor Specs
        """
        pass


if __name__ == '__main__':
    unittest.main()
