# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dat_client.models.read_sync_mode import ReadSyncMode

class TestReadSyncMode(unittest.TestCase):
    """ReadSyncMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReadSyncMode(self):
        """Test ReadSyncMode"""
        # inst = ReadSyncMode()

if __name__ == '__main__':
    unittest.main()
