# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dat_client.models.dat_core_pydantic_models_configured_document_stream_write_sync_mode import DatCorePydanticModelsConfiguredDocumentStreamWriteSyncMode

class TestDatCorePydanticModelsConfiguredDocumentStreamWriteSyncMode(unittest.TestCase):
    """DatCorePydanticModelsConfiguredDocumentStreamWriteSyncMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDatCorePydanticModelsConfiguredDocumentStreamWriteSyncMode(self):
        """Test DatCorePydanticModelsConfiguredDocumentStreamWriteSyncMode"""
        # inst = DatCorePydanticModelsConfiguredDocumentStreamWriteSyncMode()

if __name__ == '__main__':
    unittest.main()
