# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dat_api_sdk.api.connections_api import ConnectionsApi


class TestConnectionsApi(unittest.TestCase):
    """ConnectionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectionsApi()

    def tearDown(self) -> None:
        pass

    def test_create_connection_connections_post(self) -> None:
        """Test case for create_connection_connections_post

        Create Connection
        """
        pass

    def test_delete_connection_connections_connection_id_delete(self) -> None:
        """Test case for delete_connection_connections_connection_id_delete

        Delete Connection
        """
        pass

    def test_fetch_available_connections_connections_list_get(self) -> None:
        """Test case for fetch_available_connections_connections_list_get

        Fetch Available Connections
        """
        pass

    def test_read_connection_connections_connection_id_get(self) -> None:
        """Test case for read_connection_connections_connection_id_get

        Read Connection
        """
        pass

    def test_update_connection_connections_connection_id_put(self) -> None:
        """Test case for update_connection_connections_connection_id_put

        Update Connection
        """
        pass


if __name__ == '__main__':
    unittest.main()
