# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dat_client.api.workspace_users_api import WorkspaceUsersApi


class TestWorkspaceUsersApi(unittest.TestCase):
    """WorkspaceUsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkspaceUsersApi()

    def tearDown(self) -> None:
        pass

    def test_create_workspace_user_workspace_users_post(self) -> None:
        """Test case for create_workspace_user_workspace_users_post

        Create Workspace User
        """
        pass

    def test_fetch_available_workspace_users_workspace_users_workspace_id_list_get(self) -> None:
        """Test case for fetch_available_workspace_users_workspace_users_workspace_id_list_get

        Fetch Available Workspace Users
        """
        pass


if __name__ == '__main__':
    unittest.main()
