# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dat_client.models.splitter_settings import SplitterSettings

class TestSplitterSettings(unittest.TestCase):
    """SplitterSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SplitterSettings:
        """Test SplitterSettings
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SplitterSettings`
        """
        model = SplitterSettings()
        if include_optional:
            return SplitterSettings(
                strategy = '',
                config = dat_client.models.split_by_character_recursiverly_config.SplitByCharacterRecursiverlyConfig(
                    separators = null, )
            )
        else:
            return SplitterSettings(
        )
        """

    def testSplitterSettings(self):
        """Test SplitterSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
