# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dat_document_stream import DatDocumentStream

class TestDatDocumentStream(unittest.TestCase):
    """DatDocumentStream unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatDocumentStream:
        """Test DatDocumentStream
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatDocumentStream`
        """
        model = DatDocumentStream()
        if include_optional:
            return DatDocumentStream(
                name = None,
                namespace = None,
                json_schema = None,
                dir_uris = None,
                sync_mode = 'full_refresh',
                cursor_field = None
            )
        else:
            return DatDocumentStream(
                name = None,
                sync_mode = 'full_refresh',
        )
        """

    def testDatDocumentStream(self):
        """Test DatDocumentStream"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
