# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dat_api_sdk.models.configured_document_stream import ConfiguredDocumentStream

class TestConfiguredDocumentStream(unittest.TestCase):
    """ConfiguredDocumentStream unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfiguredDocumentStream:
        """Test ConfiguredDocumentStream
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfiguredDocumentStream`
        """
        model = ConfiguredDocumentStream()
        if include_optional:
            return ConfiguredDocumentStream(
                stream = {
                    'key' : null
                    },
                namespace = None,
                sync_mode = 'full_refresh',
                destination_sync_mode = 'upsert',
                cursor_field = None,
                primary_key = None
            )
        else:
            return ConfiguredDocumentStream(
                stream = {
                    'key' : null
                    },
                namespace = None,
                sync_mode = 'full_refresh',
                destination_sync_mode = 'upsert',
        )
        """

    def testConfiguredDocumentStream(self):
        """Test ConfiguredDocumentStream"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
