# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dat_client.models.actor_instance import ActorInstance

class TestActorInstance(unittest.TestCase):
    """ActorInstance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActorInstance:
        """Test ActorInstance
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActorInstance`
        """
        model = ActorInstance()
        if include_optional:
            return ActorInstance(
                name = '',
                workspace_id = 'wkspc-uuid',
                actor_id = 'gdrive-uuid',
                user_id = '09922bd9-7872-4664-99d0-08eae42fb554',
                configuration = {
                    'key' : null
                    }
            )
        else:
            return ActorInstance(
                name = '',
                configuration = {
                    'key' : null
                    },
        )
        """

    def testActorInstance(self):
        """Test ActorInstance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
