# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.body_update_actor_instance_actor_instances_actor_instance_uuid_put import BodyUpdateActorInstanceActorInstancesActorInstanceUuidPut

class TestBodyUpdateActorInstanceActorInstancesActorInstanceUuidPut(unittest.TestCase):
    """BodyUpdateActorInstanceActorInstancesActorInstanceUuidPut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BodyUpdateActorInstanceActorInstancesActorInstanceUuidPut:
        """Test BodyUpdateActorInstanceActorInstancesActorInstanceUuidPut
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BodyUpdateActorInstanceActorInstancesActorInstanceUuidPut`
        """
        model = BodyUpdateActorInstanceActorInstancesActorInstanceUuidPut()
        if include_optional:
            return BodyUpdateActorInstanceActorInstancesActorInstanceUuidPut(
                conn_spec = {
                    'key' : null
                    },
                configured_document_stream = {
                    'key' : null
                    }
            )
        else:
            return BodyUpdateActorInstanceActorInstancesActorInstanceUuidPut(
                conn_spec = {
                    'key' : null
                    },
                configured_document_stream = {
                    'key' : null
                    },
        )
        """

    def testBodyUpdateActorInstanceActorInstancesActorInstanceUuidPut(self):
        """Test BodyUpdateActorInstanceActorInstancesActorInstanceUuidPut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
